name: Release
on:
  push:
    branches:
      - main 

permissions:
  contents: read 

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
    
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.10.0"
          cache: 'pnpm'
   
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --dev

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}